//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freedom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int OrderID { get; set; }
        public int PlaceID { get; set; }
        public System.DateTime UseTime { get; set; }
        public string EventTheme { get; set; }
        public string EventDescription { get; set; }
        public string Condition { get; set; }
        public int UserID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Place Place { get; set; }
        public virtual User User { get; set; }
    }
}
