//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freedom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int PlaceID { get; set; }
        public int AreaID { get; set; }
        public string PlaceNumber { get; set; }
        public string PlaceName { get; set; }
        public Nullable<int> PlaceSize { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}
