//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freedom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserSex { get; set; }
        public string UserBirthday { get; set; }
        public byte[] UserPhoto { get; set; }
        public string College { get; set; }
        public string Major { get; set; }
        public string Grade { get; set; }
        public string UserPhone { get; set; }
        public string UserEmail { get; set; }
        public Nullable<int> BreakTimes { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual Userprofile Userprofile { get; set; }
    }
}
